drugstore_003/Models/Empleadoes.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace drugstore_003.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleadoes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empleadoes()
        {
            this.Familiars = new HashSet<Familiars>();
            this.Liquidacions = new HashSet<Liquidacions>();
        }
    
        public int idEmpleado { get; set; }
        public Nullable<int> idDireccion { get; set; }
        public Nullable<int> tipo { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public Nullable<System.DateTime> fechaNacimiento { get; set; }
        public Nullable<double> sueldoBase { get; set; }
        public string estadoCivil { get; set; }
        public Nullable<int> dni { get; set; }
    
        public virtual Direccions Direccions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Familiars> Familiars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Liquidacions> Liquidacions { get; set; }
    }
}

drugstore_003/Controllers/EmpleadoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using drugstore_003.Models;

namespace drugstore_003.Controllers
{
    public class EmpleadoesController : Controller
    {
        private Bd_drugstore_002Entities db = new Bd_drugstore_002Entities();

        // GET: Empleadoes
        public ActionResult Index()
        {
            var empleadoes = db.Empleadoes.Include(e => e.Direccions);
            return View(empleadoes.ToList());
        }

        // GET: Empleadoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleadoes empleadoes = db.Empleadoes.Find(id);
            if (empleadoes == null)
            {
                return HttpNotFound();
            }
            List<Familiars> lista = db.Familiars.Where(f => f.idEmpleado == id).ToList();
            ViewBag.ListaFamiliar = lista;
            return View(empleadoes);
        }

        /*
         public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleadoes empleadoes = db.Empleadoes.Find(id);
            if (empleadoes == null)
            {
                return HttpNotFound();
            }
            return View(empleadoes);
        }
             */


        // GET: Empleadoes/Create
        public ActionResult Create()
        {
            List<Provincias> lista = db.Provincias.ToList();
            ViewBag.ListaProvincia = new SelectList(lista, "idProvincia", "nombre");
            return View();
        }

        public JsonResult GetLocalidades(int idProvincia)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Localidads> lista = db.Localidads.Where(x => x.idProvincia == idProvincia).ToList();
            return Json(lista, JsonRequestBehavior.AllowGet);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmpleadoCLS empleado)
        {
            if (!ModelState.IsValid)
            {
                List<Provincias> lista = db.Provincias.ToList();
                ViewBag.ListaProvincia = new SelectList(lista, "idProvincia", "nombre");
                return View(empleado);
            }



            Direccions dir = new Direccions();
            dir.calle = empleado.calle;
            dir.numero = empleado.numero;
            dir.codigoPostal = empleado.codigoPostal;
            db.Direccions.Add(dir);
            db.SaveChanges();

            Empleadoes emp = new Empleadoes();
            emp.tipo = empleado.tipo;
            emp.nombre = empleado.nombre;
            emp.apellido = empleado.apellido;
            emp.fechaNacimiento = empleado.fechaNacimiento;
            emp.sueldoBase = empleado.sueldoBase;
            emp.estadoCivil = empleado.estadoCivil;
            emp.dni = empleado.dni;
            Direccions direccion = db.Direccions.Where(x => x.calle == empleado.calle && x.numero == empleado.numero).FirstOrDefault();
            emp.idDireccion = direccion.idDireccion;
            db.Empleadoes.Add(emp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DeleteFamiliar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Familiars familiars = db.Familiars.Find(id);
            if (familiars == null)
            {
                return HttpNotFound();
            }
            return View(familiars);
        }

        [HttpPost]
        public ActionResult DeleteFamiliar(int id)
        {
            Familiars familiars = db.Familiars.Find(id);
            int idE = (int)familiars.idEmpleado;
            db.Familiars.Remove(familiars);
            db.SaveChanges();
            return RedirectToAction("Details/"+idE);
        }

        public ActionResult DetailsFamiliar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Familiars familiars = db.Familiars.Find(id);
            if (familiars == null)
            {
                return HttpNotFound();
            }
            return View(familiars);
        }

        public ActionResult EditFamiliar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Familiars familiars = db.Familiars.Find(id);
            if (familiars == null)
            {
                return HttpNotFound();
            }
            ViewBag.idEmpleado = new SelectList(db.Empleadoes, "idEmpleado", "nombre", familiars.idEmpleado);
            return View(familiars);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditFamiliar([Bind(Include = "idFamiliar,idEmpleado,Parentezco,nombre,apellido,fechaNacimiento")] Familiars familiars)
        {
            if (ModelState.IsValid)
            {
                db.Entry(familiars).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details/"+familiars.idEmpleado);
            }
            ViewBag.idEmpleado = new SelectList(db.Empleadoes, "idEmpleado", "nombre", familiars.idEmpleado);
            return View(familiars);
        }

        public ActionResult CreateFamiliar()
        {
            ViewBag.idEmpleado = new SelectList(db.Empleadoes, "idEmpleado", "nombre");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateFamiliar([Bind(Include = "idFamiliar,idEmpleado,Parentezco,nombre,apellido,fechaNacimiento")] Familiars familiars)
        {
            if (ModelState.IsValid)
            {
                db.Familiars.Add(familiars);
                db.SaveChanges();
                return RedirectToAction("Details/"+familiars.idEmpleado);
            }

            ViewBag.idEmpleado = new SelectList(db.Empleadoes, "idEmpleado", "nombre", familiars.idEmpleado);
            return View(familiars);
        }
        /*

        // GET: Empleadoes/Create
        public ActionResult Create()
        {
            ViewBag.idDireccion = new SelectList(db.Direccions, "idDireccion", "calle");
            return View();
        }

        // POST: Empleadoes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "idEmpleado,idDireccion,tipo,nombre,apellido,fechaNacimiento,sueldoBase,estadoCivil,dni")] Empleadoes empleadoes)
        {
            if (ModelState.IsValid)
            {
                db.Empleadoes.Add(empleadoes);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.idDireccion = new SelectList(db.Direccions, "idDireccion", "calle", empleadoes.idDireccion);
            return View(empleadoes);
        }

        */

        // GET: Empleadoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleadoes empleadoes = db.Empleadoes.Find(id);
            if (empleadoes == null)
            {
                return HttpNotFound();
            }
            ViewBag.idDireccion = new SelectList(db.Direccions, "idDireccion", "calle", empleadoes.idDireccion);
            return View(empleadoes);
        }

        


        // POST: Empleadoes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "idEmpleado,idDireccion,tipo,nombre,apellido,fechaNacimiento,sueldoBase,estadoCivil,dni")] Empleadoes empleadoes)
        {
            if (ModelState.IsValid)
            {
                db.Entry(empleadoes).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idDireccion = new SelectList(db.Direccions, "idDireccion", "calle", empleadoes.idDireccion);
            return View(empleadoes);
        }

        // GET: Empleadoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Empleadoes empleadoes = db.Empleadoes.Find(id);
            if (empleadoes == null)
            {
                return HttpNotFound();
            }
            return View(empleadoes);
        }

        // POST: Empleadoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Empleadoes empleadoes = db.Empleadoes.Find(id);
            foreach(var familia in db.Familiars.Where(f => f.idEmpleado == empleadoes.idEmpleado))
            {
                db.Familiars.Remove(familia);
            }
            db.SaveChanges();
            db.Empleadoes.Remove(empleadoes);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

drugstore_003/Views/Empleadoes/Create.cshtml
@model drugstore_003.Models.EmpleadoCLS

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Empleadoes</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.idProvincia, "idProvincia", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.idProvincia, ViewBag.ListaProvincia as SelectList, "--Seleccione--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idProvincia, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.codigoPostal, "codigoPostal", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.codigoPostal, new SelectList(""), "--Seleccione Localidad--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.codigoPostal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.calle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.calle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.calle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.numero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.numero, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.numero, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            var listado = new List<SelectListItem>()
{
                new SelectListItem()
                {
                    Text = "Administrador",
                    Value = "1"
                },
                new SelectListItem()
                {
                    Text = "Vendedor",
                    Value = "2"
                }
            };
        }

        <div class="form-group">
            @Html.LabelFor(model => model.tipo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.tipo, listado, "--Seleccione--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.tipo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sueldoBase, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sueldoBase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sueldoBase, "", new { @class = "text-danger" })
            </div>
        </div>

        @{
            var listado2 = new List<SelectListItem>()
{
                new SelectListItem()
                {
                    Text = "Soltero/a",
                    Value = "1"
                },
                new SelectListItem()
                {
                    Text = "Casado/a",
                    Value = "2"
                },
                new SelectListItem()
                {
                    Text = "Viudo/a",
                    Value = "3"
                }
            };
        }


        <div class="form-group">
            @Html.LabelFor(model => model.estadoCivil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.estadoCivil, listado2, "--Seleccione--", new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.estadoCivil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.dni, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dni, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dni, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script src="~/Scripts/jquery-3.3.1.min.js"></script>
<script>
    $(document).ready(function () {
        $("#idProvincia").change(function () {
            $.get("/Empleadoes/GetLocalidades", { idProvincia: $("#idProvincia").val() }, function (data) {
                $("#codigoPostal").empty();
                $.each(data, function (index, row) {
                    $("#codigoPostal").append("<option value='" + row.codigoPostal + "'> " + row.nombre + "</option>")
                });
            });
        })
    });
</script>

drugstore_003/Views/Empleadoes/CreateFamiliar.cshtml
@model drugstore_003.Models.Familiars

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Familiars</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idEmpleado, "idEmpleado", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idEmpleado", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idEmpleado, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Parentezco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Parentezco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Parentezco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.fechaNacimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.fechaNacimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.fechaNacimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

drugstore_003/Views/Empleadoes/Delete.cshtml
@model drugstore_003.Models.Empleadoes

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Empleadoes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sueldoBase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sueldoBase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccions.calle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccions.calle)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Regresar", "Index")
        </div>
    }
</div>

drugstore_003/Views/Empleadoes/DeleteFamiliar.cshtml
@model drugstore_003.Models.Familiars

@{
    ViewBag.Title = "Delete";
    var id_familiar = Model.idFamiliar;
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Familiars</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idFamiliar)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idFamiliar)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Parentezco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parentezco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleadoes.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleadoes.nombre)
        </dd>

    </dl>
</div>

@using (Html.BeginForm("DeleteFamiliar", "Empleadoes", FormMethod.Post))
{
    @Html.HiddenFor(model => model.idFamiliar)

<div class="form-actions no-color">
    <input type="submit" value="Delete" class="btn btn-default" /> |
    @Html.ActionLink("Back to List", "Details/" + Model.idEmpleado)
</div>
}

drugstore_003/Views/Empleadoes/Details.cshtml
@model drugstore_003.Models.Empleadoes

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Empleadoes</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.tipo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.tipo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.sueldoBase)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.sueldoBase)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.estadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.estadoCivil)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.dni)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.dni)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccions.calle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccions.calle)
        </dd>

    </dl>
</div>



<p>
    @Html.ActionLink("Agregar Familiar", "CreateFamiliar")
</p>

<table class="table">
    <tr>
        <th>nombre</th>
        <th>apellido</th>
        <th>parentezco</th>
        <th></th>
    </tr>

    @foreach (var item in ViewBag.ListaFamiliar)
    {
        <tr>
            <td>@item.nombre</td>
            <td>@item.apellido</td>
            <td>@item.Parentezco</td>
            <td>
                @Html.ActionLink("Edit", "EditFamiliar", new { id = item.idFamiliar }) |
                @Html.ActionLink("Details", "DetailsFamiliar", new { id = item.idFamiliar }) |
                @Html.ActionLink("Delete", "DeleteFamiliar", new { id = item.idFamiliar })
            </td>

        </tr>
    }

</table>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.idEmpleado }) |
    @Html.ActionLink("Regresar", "Index")
</p>

drugstore_003/Views/Empleadoes/DetailsFamiliar.cshtml
@model drugstore_003.Models.Familiars

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Familiars</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Parentezco)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Parentezco)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.fechaNacimiento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaNacimiento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Empleadoes.nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Empleadoes.nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditFamiliar", new { id = Model.idFamiliar }) |
    @Html.ActionLink("Back to List", "Details/"+Model.idEmpleado)
</p>